Servico de animizacao por tempo de permanencia com rota
isabellefo/seg-informacao pull request #25
Opened 2021-05-12 03:03 UTC by isabellefo

Anonimização dos clientes que a última transação ocorreu há mais de 24 meses.

Rota da requisição:
`PUT /cliente/dado-pessoal/anonimizar/tempo`

`curl --location --request PUT "http://localhost:5000/cliente/dado-pessoal/anonimizar/tempo"`

2021-05-12 11:12 UTC, gfborges commented
Obrigado por colocar o curl :P, facilita minha vida

2021-05-12 11:14 UTC, gfborges commented on petshop/cliente/Cliente.py
> +    def get_id(self):
o id_cliente é publico, pode acessar ele diretamente. Não precisa de getter para isso em python

2021-05-12 11:44 UTC, gfborges requested changes

2021-05-12 11:44 UTC, gfborges commented on petshop/cliente/Cliente.py
> +        return self.id_cliente
Não é necessário criar um getter para id, ele é público

2021-05-12 11:44 UTC, gfborges commented on petshop/cliente/service.py
> +                db_session.add(cliente)
Qual é a útilidade da variável clientesT ? O tempo de permanência não era uma variável que viria do end-point ?

2021-05-12 11:44 UTC, gfborges commented on petshop/transacao/Transacao.py
> +
excluir código comentado

2021-05-12 11:44 UTC, gfborges commented on petshop/cliente/Cliente.py
> +            return dt.data_transacao
Tem certeza que isso pega sempre a última transação ? Poderia usar max e o argumento key
```py
a = [{"a": 1}, {"b": 2}]
max(a, key = lambda x: x["a"]) # {"b": 2}
```

2021-05-12 11:44 UTC, gfborges commented on petshop/cliente/Cliente.py
> +
Se ele não tem transações seria bom pegar a data de cadastro.
Melhoria opcional

2021-05-12 11:49 UTC, isabellefo commented on petshop/cliente/service.py
> +                db_session.add(cliente)
Nenhuma, era pra um teste, esqueci de tirar, mals.

2021-05-12 11:49 UTC, isabellefo commented on petshop/cliente/Cliente.py
> +        return self.id_cliente
Ah, tô ligada, era pra um teste, esqueci de tirar, mals.

2021-05-15 00:35 UTC, gfborges approved these changes

2021-05-15 00:35 UTC, merged